package CoffeeShop.GUI.bill;

import CoffeeShop.Obj.Bill;
import CoffeeShop.Util.Common;
import CoffeeShop.Util.DbUtil;
import java.awt.Color;
import java.text.SimpleDateFormat;

import javax.swing.*;

public final class JDSearchBill extends javax.swing.JDialog {

    private CallbackBillSearch callback;
    private Bill bill;
    private DbUtil dbUtil;

    interface CallbackBillSearch {
        public void actionBillSearch(Bill bill, String dateStart, String dateEnd);
    }

    public JDSearchBill(java.awt.Frame parent, boolean modal, DbUtil dbUtil, CallbackBillSearch callback) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.dbUtil = dbUtil;
        this.callback = callback;

        // Custom Style
        txtUserId.setBorder(BorderFactory.createCompoundBorder(
                txtUserId.getBorder(),
                BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        txtTableName.setBorder(BorderFactory.createCompoundBorder(
                txtTableName.getBorder(),
                BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        txtTimeStart.setBorder(BorderFactory.createCompoundBorder(
                txtTimeStart.getBorder(),
                BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        txtTimeEnd.setBorder(BorderFactory.createCompoundBorder(
                txtTimeEnd.getBorder(),
                BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        lblTimeError.setVisible(false);
        lblTimeError1.setVisible(false);
        lblIdError.setVisible(false);
        
        cboStatus.removeAllItems();
        DefaultComboBoxModel<String> dcbm = new DefaultComboBoxModel<>();
        dcbm.addElement("Không chọn");
        dcbm.addElement("Đã thanh toán");
        dcbm.addElement("Chưa thanh toán");
        cboStatus.setModel(dcbm);
    }
    
    private static boolean isValidDate (String dateStr) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        try {
            sdf.parse(dateStr);
        } 
        catch (Exception e) {
            return false;
        }
        return true;       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        cboStatus = new javax.swing.JComboBox<>();
        txtTimeStart = new javax.swing.JTextField();
        lblUserId = new javax.swing.JLabel();
        lblTableName = new javax.swing.JLabel();
        txtTableName = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        txtTimeEnd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblTimeError = new javax.swing.JLabel();
        lblTimeError1 = new javax.swing.JLabel();
        lblIdError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TÌM KIẾM HOÁ ĐƠN");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_google_web_search_50px.png"))); // NOI18N
        jLabel1.setText("TÌM KIẾM HOÁ ĐƠN");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Trạng thái");

        btnSearch.setBackground(new java.awt.Color(0, 204, 106));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Tìm kiếm");
        btnSearch.setBorderPainted(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblUserId.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblUserId.setText("Mã nhân viên");

        lblTableName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTableName.setText("Tên bàn");

        lblTime.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lblTime.setText("Thời gian");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("đến");

        lblTimeError.setForeground(new java.awt.Color(240, 71, 71));
        lblTimeError.setText("Nhập đúng định dạng yyyy-mm-dd");

        lblTimeError1.setForeground(new java.awt.Color(240, 71, 71));
        lblTimeError1.setText("Nhập đúng định dạng yyyy-mm-dd");

        lblIdError.setForeground(new java.awt.Color(240, 71, 71));
        lblIdError.setText("Mã nhân viên là một số nguyên dương");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUserId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTableName)
                    .addComponent(txtUserId)
                    .addComponent(lblTableName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTimeError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTimeError1)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIdError)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIdError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimeStart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimeError)
                    .addComponent(lblTimeError1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //set default
        txtUserId.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(Color.BLACK),
                    BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        lblUserId.setForeground(Color.BLACK);
        txtTimeStart.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(Color.BLACK),
                    BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        txtTimeEnd.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(Color.BLACK),
                    BorderFactory.createEmptyBorder(5, 8, 5, 8)));
        lblTimeError1.setVisible(false);
        lblTimeError.setVisible(false);
        lblIdError.setVisible(false);
        
        bill = new Bill();
        boolean valid = true;
        
        String dateStart = null;
        String dateEnd = null;
        
        if (!Common.isNullOrEmpty(txtTimeStart.getText())) {
            if (!isValidDate(txtTimeStart.getText())) {
                valid = false;                
                txtTimeStart.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(Color.RED),
                    BorderFactory.createEmptyBorder(5, 8, 5, 8)));
                lblTimeError.setVisible(true);
            }
            else 
                dateStart = txtTimeStart.getText();
        }
        
        if (!Common.isNullOrEmpty(txtTimeEnd.getText())) {
            if (!isValidDate(txtTimeEnd.getText())) {
                valid = false;  
                txtTimeEnd.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(Color.RED),
                    BorderFactory.createEmptyBorder(5, 8, 5, 8))); 
                lblTimeError1.setVisible(true);
            }
            else 
                dateEnd = txtTimeEnd.getText();
        }

        if (!Common.isNullOrEmpty(txtUserId.getText())) {
            if (!Common.isInteger(txtUserId.getText())) {
                valid = false;  
                txtUserId.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(Color.RED),
                    BorderFactory.createEmptyBorder(5, 8, 5, 8))); 
                lblIdError.setVisible(true);
            }
            else 
                bill.setUser_id(Integer.valueOf(txtUserId.getText().trim()));
        }
        
        if (valid) {       
            if (!Common.isNullOrEmpty(txtTableName.getText().trim())) 
                bill.setTable_name(txtTableName.getText().trim());

            if (!"Không chọn".equals(cboStatus.getSelectedItem().toString())) 
                bill.setStatus("Đã thanh toán".equals(cboStatus.getSelectedItem().toString()));

            callback.actionBillSearch(bill, dateStart, dateEnd);
            dispose();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIdError;
    private javax.swing.JLabel lblTableName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimeError;
    private javax.swing.JLabel lblTimeError1;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JTextField txtTableName;
    private javax.swing.JTextField txtTimeEnd;
    private javax.swing.JTextField txtTimeStart;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables
}
