package CoffeeShop.GUI.bill;

import CoffeeShop.DAO.impl.BillDao;
import CoffeeShop.DAO.impl.BillDetailDao;
import CoffeeShop.Obj.Bill;
import CoffeeShop.Obj.BillDetail;
import CoffeeShop.Obj.User;
import CoffeeShop.Util.Common;
import CoffeeShop.Util.DbUtil;

import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class PnlBill extends javax.swing.JPanel implements JDSearchBill.CallbackBillSearch, JDDeleteBill.CallbackBillDelete {
    private Frame parent;
    private DbUtil dbUtil;
    private Bill bill;
    private List<Bill> bills = new ArrayList<>();
    private BillDao billDao;
    private List<BillDetail> billDetails = null;
    private BillDetailDao billDetailDao = null;

    public PnlBill(Frame parent, DbUtil dbUtil, User user) {
        initComponents();
        this.parent = parent;
        this.dbUtil = dbUtil;
        this.billDao = new BillDao(dbUtil);
        
        if (user.getRole() == 0) 
            lblDelete.setVisible(false);
        else
            lblDelete.setVisible(true);

        loading(null, null, null);
    }
    private void loading(Bill newBill, String dateStart, String dateEnd) {
        bill = null;
        tblBill.removeAll();
        bills = billDao.getAll(newBill, dateStart, dateEnd);

        String columns[] = {"ID", "Nhân viên", "Bàn", "Tổng tiền", "Trạng thái", "Thời gian"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0);
        long allTotalPrice = 0;

        if (!Common.isNullOrEmpty(bills)) {
            for (Bill obj : bills) {
                dtm.addRow(new Object[]{obj.getId(), obj.getUser_name(), obj.getTable_name(), NumberFormat.getInstance().format(obj.getTotal_price()), obj.getStatus() ? "Đã thanh toán" : "Chưa thanh toán", obj.getCreated_at()});
                if (obj.getStatus()) 
                    allTotalPrice += obj.getTotal_price();
            }

            tblBill.getSelectionModel().addListSelectionListener((ListSelectionEvent lse) -> {
                int position = tblBill.getSelectedRow();
                if (position >= 0) 
                    bill = bills.get(position);

            });
            txtTotalBill.setText(NumberFormat.getInstance().format(allTotalPrice));
            tblBill.changeSelection(0, 0, false, false);
        }

        tblBill.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuCheckOut = new javax.swing.JMenuItem();
        jMenuShow = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        lblDelete = new javax.swing.JLabel();
        lblRefresh = new javax.swing.JLabel();
        lblExport = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblTotalBill = new javax.swing.JLabel();
        txtTotalBill = new javax.swing.JTextField();

        jMenuCheckOut.setText("Thanh toán");
        jMenuCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCheckOutActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuCheckOut);

        jMenuShow.setText("Xem ");
        jMenuShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuShowActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuShow);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 50, 20));

        lblSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_search_50px_1.png"))); // NOI18N
        lblSearch.setText("Tìm kiếm");
        lblSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
        });
        jPanel2.add(lblSearch);

        lblDelete.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_delete_50px.png"))); // NOI18N
        lblDelete.setText("Xoá");
        lblDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteMouseClicked(evt);
            }
        });
        jPanel2.add(lblDelete);

        lblRefresh.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblRefresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_repeat_50px_1.png"))); // NOI18N
        lblRefresh.setText("Làm mới");
        lblRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRefreshMouseClicked(evt);
            }
        });
        jPanel2.add(lblRefresh);

        lblExport.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblExport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_print_50px.png"))); // NOI18N
        lblExport.setText("Xuất hoá đơn");
        lblExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblExport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblExport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExportMouseClicked(evt);
            }
        });
        jPanel2.add(lblExport);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        tblBill.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblBill.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblBill.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBillMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBill);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(599, 114));

        lblTotalBill.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblTotalBill.setText("Tổng tiền thu về");

        txtTotalBill.setEditable(false);
        txtTotalBill.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtTotalBill.setFocusable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(487, Short.MAX_VALUE)
                .addComponent(lblTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        JDSearchBill jdsb = new JDSearchBill(parent, true, dbUtil, this);
        jdsb.setVisible(true);
    }//GEN-LAST:event_lblSearchMouseClicked

    private void lblDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseClicked
        if (!Common.isNullOrEmpty(bill)) {
            JDDeleteBill deleteBill = new JDDeleteBill(parent, true, dbUtil, this, bill);
            deleteBill.setVisible(true);
        }
    }//GEN-LAST:event_lblDeleteMouseClicked

    private void lblRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefreshMouseClicked
        loading(null, null, null);
    }//GEN-LAST:event_lblRefreshMouseClicked

    private void lblExportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExportMouseClicked
        if (!bill.getStatus())
            JOptionPane.showMessageDialog(this, "Bạn không thể xuất hoá đơn chưa thanh toán");
        else {
            try {
                ExportBill eb = new ExportBill(parent, true, dbUtil, bill);
            } catch (ParseException ex) {
                Logger.getLogger(PnlBill.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_lblExportMouseClicked

    private void tblBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBillMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3 && !Common.isNullOrEmpty(bill)) { //right click
            jPopupMenu1.show(tblBill, evt.getX(), evt.getY());
        }
        if (bill.getStatus()) jMenuCheckOut.setVisible(false);
        else jMenuCheckOut.setVisible(true);
    }//GEN-LAST:event_tblBillMouseClicked

    private void jMenuCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCheckOutActionPerformed
        try {
            bill.setStatus(true);

            Map<String, Object> billCheckout = billDao.update(bill);

            if ((boolean) billCheckout.get("status") == true) {
                JOptionPane.showMessageDialog(this, billCheckout.get("message"));
                loading(null, null, null);
            } 
            else 
                JOptionPane.showMessageDialog(this, billCheckout.get("message"));

        } catch (HeadlessException | NumberFormatException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuCheckOutActionPerformed

    private void jMenuShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuShowActionPerformed
        if (!Common.isNullOrEmpty(bill)) {
            JDBill jdb = new JDBill(parent, true, dbUtil, bill);
            jdb.setVisible(true);
        }
    }//GEN-LAST:event_jMenuShowActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuCheckOut;
    private javax.swing.JMenuItem jMenuShow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblExport;
    private javax.swing.JLabel lblRefresh;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTotalBill;
    private javax.swing.JTable tblBill;
    private javax.swing.JTextField txtTotalBill;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionBillDelete() {
        loading(null, null, null);
    }

    @Override
    public void actionBillSearch(Bill bill, String dateStart, String dateEnd) {
        loading(bill, dateStart, dateEnd);
    }
}
