package CoffeeShop.GUI.home;

import CoffeeShop.Obj.User;
import CoffeeShop.GUI.area.PnlArea;
import CoffeeShop.GUI.bill.PnlBill;
import CoffeeShop.GUI.category.PnlCategory;
import CoffeeShop.GUI.product.PnlProduct;
import CoffeeShop.GUI.user.PnlUser;
import CoffeeShop.Util.DbUtil;

import java.awt.*;
import javax.swing.JButton;

public final class Dashboard extends javax.swing.JFrame implements JDLogin.CallbackLogin {
    
    private User user;
    private JDLogin jDLogin;
    private DbUtil dbUtil;

    public Dashboard(DbUtil dbUtil) {
        initComponents();
        this.dbUtil = dbUtil;

        this.jDLogin = new JDLogin(this, true, dbUtil, this);
        jDLogin.setVisible(true);
    }

    public void loadUser(User user) {
        this.user = user;
        lblName.setText(user.getName().toUpperCase());
        lblEmail.setText(user.getEmail());
        this.setVisible(true);          
        btnLogOut.setForeground(new Color(52,152,219));

        if (user.getRole() != 1) {
            lblUser.setVisible(false);
            btnUser.setVisible(false);
        }
        else {
            lblUser.setVisible(true);
            btnUser.setVisible(true);
        }

        btnDashboard.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        lblDashboard = new javax.swing.JLabel();
        btnCategory = new javax.swing.JButton();
        lblCategory = new javax.swing.JLabel();
        btnProduct = new javax.swing.JButton();
        lblProduct = new javax.swing.JLabel();
        btnBill = new javax.swing.JButton();
        lblArea = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnArea = new javax.swing.JButton();
        lblBill = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        pnlBody = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ QUÁN CÀ PHÊ");
        setBackground(new java.awt.Color(255, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1000, 600));

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));

        lblName.setFont(new java.awt.Font("Leelawadee UI", 1, 20)); // NOI18N
        lblName.setForeground(new java.awt.Color(44, 62, 80));
        lblName.setText("Tên");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(127, 140, 141));
        lblEmail.setText("gmail");

        btnDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(44, 62, 80));
        btnDashboard.setText("Trang chủ");
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard.setContentAreaFilled(false);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setFocusable(false);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        lblDashboard.setBackground(new java.awt.Color(0, 204, 106));
        lblDashboard.setOpaque(true);

        btnCategory.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        btnCategory.setForeground(new java.awt.Color(44, 62, 80));
        btnCategory.setText("Danh mục");
        btnCategory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCategory.setContentAreaFilled(false);
        btnCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategory.setFocusable(false);
        btnCategory.setPreferredSize(new java.awt.Dimension(100, 27));
        btnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryActionPerformed(evt);
            }
        });

        lblCategory.setBackground(new java.awt.Color(255, 255, 255));
        lblCategory.setOpaque(true);

        btnProduct.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        btnProduct.setForeground(new java.awt.Color(44, 62, 80));
        btnProduct.setText("Sản phẩm");
        btnProduct.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnProduct.setContentAreaFilled(false);
        btnProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduct.setFocusable(false);
        btnProduct.setPreferredSize(new java.awt.Dimension(100, 27));
        btnProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductActionPerformed(evt);
            }
        });

        lblProduct.setBackground(new java.awt.Color(255, 255, 255));
        lblProduct.setOpaque(true);
        lblProduct.setPreferredSize(new java.awt.Dimension(100, 0));

        btnBill.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnBill.setForeground(new java.awt.Color(44, 62, 80));
        btnBill.setText("Hoá đơn");
        btnBill.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBill.setContentAreaFilled(false);
        btnBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBill.setFocusable(false);
        btnBill.setPreferredSize(new java.awt.Dimension(100, 27));
        btnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillActionPerformed(evt);
            }
        });

        lblArea.setBackground(new java.awt.Color(255, 255, 255));
        lblArea.setOpaque(true);
        lblArea.setPreferredSize(new java.awt.Dimension(100, 0));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(127, 140, 141));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Bạn đã đăng nhập, ");

        btnArea.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnArea.setForeground(new java.awt.Color(44, 62, 80));
        btnArea.setText("Khu vực & bàn ăn");
        btnArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnArea.setContentAreaFilled(false);
        btnArea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArea.setFocusable(false);
        btnArea.setPreferredSize(new java.awt.Dimension(100, 27));
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });

        lblBill.setBackground(new java.awt.Color(255, 255, 255));
        lblBill.setOpaque(true);
        lblBill.setPreferredSize(new java.awt.Dimension(100, 0));

        btnUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnUser.setForeground(new java.awt.Color(44, 62, 80));
        btnUser.setText("Người dùng");
        btnUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUser.setContentAreaFilled(false);
        btnUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUser.setFocusable(false);
        btnUser.setPreferredSize(new java.awt.Dimension(100, 27));
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setOpaque(true);
        lblUser.setPreferredSize(new java.awt.Dimension(100, 0));

        btnLogOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogOut.setText("Đăng xuất?");
        btnLogOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.setFocusable(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lblCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnArea, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBill, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(lblBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUser, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 363, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblName)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblBill, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlBody.setBackground(new java.awt.Color(255, 255, 255));
        pnlBody.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBody, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Quản lý quán cà phê");

        setSize(new java.awt.Dimension(1024, 595));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
        lblCategory.setBackground(Color.GREEN);

        lblDashboard.setBackground(Color.WHITE);
        lblProduct.setBackground(Color.WHITE);
        lblArea.setBackground(Color.WHITE);
        lblBill.setBackground(Color.WHITE);
        lblUser.setBackground(Color.WHITE);
        
        pnlBody.removeAll();
        PnlCategory pnl = new PnlCategory(this, dbUtil, user);
        pnlBody.add(pnl);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnCategoryActionPerformed

    private void btnProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductActionPerformed
        lblProduct.setBackground(Color.GREEN);

        lblDashboard.setBackground(Color.WHITE);
        lblCategory.setBackground(Color.WHITE);
        lblArea.setBackground(Color.WHITE);
        lblBill.setBackground(Color.WHITE);
        lblUser.setBackground(Color.WHITE);
        
        pnlBody.removeAll();
        PnlProduct pnl = new PnlProduct(this, dbUtil, user);
        pnlBody.add(pnl);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnProductActionPerformed

    private void btnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillActionPerformed
        lblBill.setBackground(Color.GREEN);

        lblDashboard.setBackground(Color.WHITE);
        lblCategory.setBackground(Color.WHITE);
        lblProduct.setBackground(Color.WHITE);
        lblArea.setBackground(Color.WHITE);
        lblUser.setBackground(Color.WHITE);
        
        pnlBody.removeAll();      
        PnlBill pnl = new PnlBill(this, dbUtil, user);
        pnlBody.add(pnl);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnBillActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        lblDashboard.setBackground(Color.GREEN);

        lblArea.setBackground(Color.WHITE);
        lblBill.setBackground(Color.WHITE);
        lblCategory.setBackground(Color.WHITE);
        lblProduct.setBackground(Color.WHITE);
        lblUser.setBackground(Color.WHITE);
        
        pnlBody.removeAll();
        PnlHome pnl = new PnlHome(this, dbUtil);
        pnlBody.add(pnl);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
        lblArea.setBackground(Color.GREEN);

        lblDashboard.setBackground(Color.WHITE);
        lblBill.setBackground(Color.WHITE);
        lblCategory.setBackground(Color.WHITE);
        lblProduct.setBackground(Color.WHITE);
        lblUser.setBackground(Color.WHITE);
        
        pnlBody.removeAll();
        PnlArea pnl = new PnlArea(this, dbUtil, user);
        pnlBody.add(pnl);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        lblUser.setBackground(Color.GREEN);

        lblArea.setBackground(Color.WHITE);
        lblDashboard.setBackground(Color.WHITE);
        lblBill.setBackground(Color.WHITE);
        lblCategory.setBackground(Color.WHITE);
        lblProduct.setBackground(Color.WHITE);
        
        pnlBody.removeAll();
        PnlUser pnl = new PnlUser(this, dbUtil, user);
        pnlBody.add(pnl);
        pnlBody.repaint();
        pnlBody.revalidate();
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        this.setVisible(false);
        this.jDLogin.setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnBill;
    private javax.swing.JButton btnCategory;
    private javax.swing.JButton btnDashboard;
    private static javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnProduct;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblBill;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionLogin(User user) {
        loadUser(user);
    }

    public static JButton getBtnLogOut() {
        return btnLogOut;
    }
}
